"""Schemas for AI triage requests and responses.

These Pydantic models describe the shape of the request body accepted
by the AI triage endpoint and the response returned by that endpoint.
They deliberately mirror the structures defined in the standalone AI
backend (Folder B) to ensure backward compatibility with existing
clients.  You should not import SQLModel classes from ``app.models``
here; instead, reference only primitive types and simple Pydantic
fields.
"""

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


class TriageRequest(BaseModel):
    """Schema for a triage request posted to the API."""

    patient_id: str = Field(..., description="Identifier of the patient for whom triage is requested.")
    call_text: str = Field(..., description="Transcript of the patient call or encounter.")
    call_timestamp: Optional[datetime] = Field(
        None,
        description=(
            "Timestamp of the call.  If omitted the server will use the current time."
        ),
    )


class TriageResponse(BaseModel):
    """Schema returned after processing a triage request."""

    triage_id: str = Field(..., description="Unique identifier of the stored triage result.")
    encounter_id: str = Field(..., description="Identifier of the created encounter.")
    patient_id: str = Field(..., description="Identifier of the patient associated with the triage.")
    summary: str = Field(..., description="Concise summary of the call generated by the AI.")
    urgency_level: int = Field(..., ge=1, le=5, description="Numeric urgency scale (1-5).")
    urgency_label: str = Field(..., description="Human‑readable urgency category.")
    recommended_action: str = Field(..., description="Recommended clinical action.")
    notes: Optional[str] = Field(
        None, description="Additional notes or flags returned by the AI."
    )
    created_at: datetime = Field(..., description="Timestamp when the triage record was created.")
